### ISSUE TITLE
Change green and blue fonts to something more normal.

### ISSUE THREAD

**Issue by zo0o0ot** [sermonarchives/blog#3]
Override theme CSS to change the initial text from Green and Blue text to something more normal looking.

The original Hugo theme is [Robust](https://github.com/dim0627/hugo_theme_robust).

I think it's italicized text that needs to be changed.

Output from Hugo looks like this: (permalink to page [here](https://sermonarchives.github.io/sermons/a-fathers-heart-he-turned-to-me-1977/))
![Screenshot from 2019-10-01 15-33-41](https://user-images.githubusercontent.com/876146/65998595-372a7200-e461-11e9-9220-9bc9cfef7499.png)

The CSS that probably causes this looks like this: https://github.com/dim0627/hugo_theme_robust/blob/master/layouts/partials/styles.css

Markdown file here: content/sermons/a-fathers-heart-he-turned-to-me-1977.md

```
_This handwritten sermon dates back to 1977, for the Fourth Sunday in Lent. He refers to a hymn that was written by Martin Luther, containing the title of the sermon in its lyrics._

<!--more-->

_The Gospel text is from Luke 15, which contains the parable of the prodigal son. As far as I can tell, the lyrics from Luther's hymn mentioned in this sermon are probably from verse four of [Dear Christians, one and all rejoice](https://books.google.com/books?id=riMkK9b5WJEC&lpg=PA75&ots=iwkRB2P93I&dq=luther%20a%20father's%20heart%20he%20turned%20to%20me&pg=PA75#v=onepage&q&f=false), if a Google Books search can be believed._
```

**Comment by thallesbrandao** [comment]
dibs

**Comment by zo0o0ot** [comment]
The blue link color comes from https://github.com/sermonarchives/blog/blob/8be58132f698742ef724f024061f2120891f64c0/layouts/partials/styles.css#L41

The green text comes from:
https://github.com/sermonarchives/blog/blob/8be58132f698742ef724f024061f2120891f64c0/layouts/partials/styles.css#L340
