### ISSUE TITLE
Image exists, but does not appear in Gitpod preview

### ISSUE THREAD

**Issue by zo0o0ot** [sermonarchives/blog#9]
![image](https://user-images.githubusercontent.com/876146/96175412-7c94d280-0ef0-11eb-8f60-6dfed2c4d05c.png)

I think that the appropriate pathing is being used, as this format is currently working on the last published version.

However, when trying to move development to GitPod, I'm no longer seeing images used in the markdown content.

It also appears that the twitter icon is not being shown.

Existing web site:
![image](https://user-images.githubusercontent.com/876146/96175680-d5fd0180-0ef0-11eb-84ad-85f3f88038b0.png)

Per @JianLoong in #7 , here is a possible explanation:

> I was just looking at GitPod, it seems the reason this happens because of the URL generated for preview purposes.
> 
> So if you actually did a
> 
> hugo server or hugo server -D
> to run it, it will not look nice because that is supposed to be for development. If you look at the generated files under public would be correct but the demo itself is not working on GitPod because it is mapped to localhost instead of the live url instead.
> 
> That being said, I tried to run the command below on GitPod instead
> 
> hugo server -b https://1313-c40017b2-ba54-4783-9c76-73b58c0603ba.ws-us02.gitpod.io -D --appendPort=false
> and it seems to be working fine. (You will need to put the correct url in the command for it to be working)
> 
> What is happening here is that I specifically ask it generated with that base url without appending the port number.

I'm wondering what the possible difference might be between the preview images and the images that are used inline on individual posts, and why that would apply the to the social icons, as well.

**Comment by JianLoong** [comment]
I think its much better not to use the original theme author **img** shortcode. It doesnt really seem to work because of the way the images are you stored for your directory structure. The hugo default figure shortcode seems to work better. I did a quick PR to fix it. It should be working as intended now.

**Comment by zo0o0ot** [comment]
I agree.  I tested the figure shortcode in GitPod, and it worked right away.
![image](https://user-images.githubusercontent.com/876146/96202820-d794ec80-0f25-11eb-8b40-305f3ee655ab.png)

**Comment by zo0o0ot** [comment]
Fixed in #11
