### ISSUE TITLE
RCL links are dead. Update them.

### ISSUE THREAD

**Issue by zo0o0ot** [sermonarchives/blog#96]
The Vanderbilt Revised Common Lectionary (RCL) site has been updated, and all of the previous links are dead.  Update the links in each sermon.

An example is here:

https://github.com/sermonarchives/blog/blob/c5915124b18ca5b2927fd353c0f9c28e856891ae/content/sermons/the-miracle-jesus-couldnt-perform-1994-0147.md?plain=1#L20

The [old link](https://lectionary.library.vanderbilt.edu/texts.php?id=77) no longer works, but Palm Sunday B still exists, even though it's now called "Liturgy of the Passion" here: https://lectionary.library.vanderbilt.edu/texts/?y=382&z=l&d=34

You can see the new links in pages that list each season such as [this one](https://lectionary.library.vanderbilt.edu/calendar/2023-24/?season=lent) for Lent.

Update all of the links that you find. There should be one in each sermon.

**Comment by zo0o0ot** [comment]
I have tried to list relevant season information in the front matter of each sermon.
https://github.com/sermonarchives/blog/blob/c5915124b18ca5b2927fd353c0f9c28e856891ae/content/sermons/the-miracle-jesus-couldnt-perform-1994-0147.md?plain=1#L5-L7

**Comment by Brijeshthummar02** [comment]
i can fix this, assign me the task.

**Comment by zo0o0ot** [comment]
Sure. One more bit of context - the links will resolve in the internet wayback machine, as there appears to be a backup that was made of the site there:
https://web.archive.org/web/20240420130435/https://lectionary.library.vanderbilt.edu/texts.php?id=77
![image](https://github.com/user-attachments/assets/36c5967b-dc22-43f9-bb69-97f084f1ca1d)

Also, there's probably about 50-100 links. You can split your PRs into groups of 5-15 if that's easier.

**Comment by zo0o0ot** [comment]
To make the work easier, I'm fixing some links, too, starting with the last sermons (alphabetically), such as the fixes in #97 and #98.

**Comment by Brijeshthummar02** [comment]
i'll fix it also i need some time as my university exams are coming.

**Comment by zo0o0ot** [comment]
I hope exams are going well. Any news on when you'll be taking a look at this?

**Comment by zo0o0ot** [comment]
@Brijeshthummar02 Any updates? Are exams over?

**Comment by Brijeshthummar02** [comment]
i think it will take a long time to fix all links, anyways i will try my best.

**Comment by zo0o0ot** [comment]
My suggestion is to fix 5 links and make a PR, and we can review the process and go from there.

**Comment by zo0o0ot** [comment]
@Brijeshthummar02 We are now at the end of Hacktoberfest. Do you still want to be assigned to this issue moving forward?

**Comment by Brijeshthummar02** [comment]
I think you can assign others if they wanna work on it.

**Comment by zo0o0ot** [comment]
Fixed in #97, #98 , and #100 .  If any other links are broken, I'll make a different issue, but everything that mentioned texts.php is no longer present in the content.
